name: flutter_bluetooth_printer
description: Image based printing for bluetooth thermal printer, support for iOS and Android.
version: 1.1.10
repository: https://github.com/ekasetiawans/flutter_bluetooth_printer_plugin

environment:
  sdk: ">=2.12.0 <4.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter

  image: ">=2.0.0 <=5.0.0"
  esc_pos_utils_plus: ">=2.0.0 <5.0.0"
#  pdf: ">=3.0.0 <4.0.0"
#   native_pdf_renderer: ">=3.0.0 <4.0.0"
# native_pdf_renderer: ^5.0.0+1
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  plugin:
    platforms:
      android:
        package: id.flutter.plugins
        pluginClass: FlutterBluetoothPrinterPlugin
      ios:
        pluginClass: FlutterBluetoothPrinterPlugin
